### ISSUE TITLE
Problem redirecting links for not logged in users

### ISSUE THREAD

**Issue by mathias-rosa** [Eirbware/cassis#8]
**Steps to reproduce**

- Create a protected link
- open the link in a private tab

**Comment by NemoDacremont** [comment]
Solutions possibles : 
* Laisser le front-end de cassis gérer la redirection en utilisant du stockage local comme LocalStorage (je pense que c'est une mauvaise ideé)
* Propager en query du login un chemin de redirection (ex: https://cassis.eirb.fr/jsp -> https://cassis.eirb.fr/login?r=jsp&ticket="le ticket d'auth d'eirbconnect") permettrait de le faire, mais nécessite un changement dans eirbconnect

Il va falloir faire des modifications sur Eirbconnect d'abord :

actuellement, seule une URL est acceptée par eirbconnect : https://cassis.eirb.fr/login, et on ne peut pas passer des query en paramètre pour gérer une redirection, car eirbconnect utilise un hash md5 de l'url d'origine pour rediriger après authentification.

Eirbconnect pourrait fonctionner en repassant les query d'origine à chaque requête dans une autre query, de façon à retrouver toujours la même url du service.

Ce n'est pas clair, mais le hack serait : 
* https://cassis.eirb.fr/jsp
* -> https://connect.eirb.fr/auth?service=https://cassis.eirb.fr/login?r=jsp
* -> https://connect.eirb.fr/auth?service=https://cassis.eirb.fr/auth/hash_md5?query="?r=jsp"
* ...
* -> https://cassis.eirb.fr/login + query + "ticket=ticket d'authentification"

Cependant, je pense que ça met plus en avant un problème de design de cassis, qui devrait valider des services avec une regex, ou quelque chose de plus souple, ajouter ce système de query serait un hack lourd à implémenter et à maintenir.

**Comment by mathias-rosa** [comment]
Je suis d'accord avec toi, la première option marcherait mais c'est plus un problème de eirbconnect. 
La deuxième solution que tu propose est pas mal mais je pense qu'une meilleure solution serait que eirbconnect whitelist l'url de base du site et encrypte le reste de l'url afin qu'on puisse l'envoyer sans problème aux fournisseurs d'identité sans faire fuiter d'informations et sans produire de bugs de parsing d'url.

On pourrait avoir a peu près ça :  
- https://cassis.eirb.fr/r/P**saJ)
- https://connect.eirb.fr/login?eirb_service_url=https://cassis.eirb.fr/r/P**saJ)
> On vérifie que eirb.fr est whitelist ou que cassis.eirb.fr est whitelist puis on encrypte l'url, pourquoi pas dans un jwt ?
- https://cas.bordeaux-inp.fr/login?service=https://connect.eirb.fr/auth/<url encryptée>
- https://connect.eirb.fr/auth/<url encryptée>
- https://cassis.eirb.fr/r/P**saJ)
